server:
  port: 8091

spring:
  application:
    name: issuerMs
     
  datasource:
    password: Dipak@1999
    url: jdbc:mysql://localhost:3306/BookDetails?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
    
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      
bookMs:
  base:
    url: http://localhost:8090/api/v1     
     